# Simulated daily request to your Render project so that the service doesn't go down
name: Daily render ping

on:
  schedule:
    # Midnight IST (18:30 UTC the previous day)
    - cron: '30 18 * * *'
    # Noon IST (06:30 UTC)
    - cron: '30 6 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
      - name: Run cURL on Website
        run: curl -I https://your-render-app.onrender.com
